
package edu.uade.tpo.ingsist2.integration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "getCotizacionRodamiento", targetNamespace = "http://facade.view.ingsist2.tpo.uade.edu/", wsdlLocation = "http://10.10.90.135:8080/TPO-IngSist2-EAR-TPO-IngSist2-EJB-0.0.1-SNAPSHOT/FacadeBean?wsdl")
public class GetCotizacionRodamiento_Service
    extends Service
{

    private final static URL GETCOTIZACIONRODAMIENTO_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://10.10.90.135:8080/TPO-IngSist2-EAR-TPO-IngSist2-EJB-0.0.1-SNAPSHOT/FacadeBean?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GETCOTIZACIONRODAMIENTO_WSDL_LOCATION = url;
    }

    public GetCotizacionRodamiento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCotizacionRodamiento_Service() {
        super(GETCOTIZACIONRODAMIENTO_WSDL_LOCATION, new QName("http://facade.view.ingsist2.tpo.uade.edu/", "getCotizacionRodamiento"));
    }

    /**
     * 
     * @return
     *     returns GetCotizacionRodamiento
     */
    @WebEndpoint(name = "getCotizacionRodamientoPort")
    public GetCotizacionRodamiento getGetCotizacionRodamientoPort() {
        return (GetCotizacionRodamiento)super.getPort(new QName("http://facade.view.ingsist2.tpo.uade.edu/", "getCotizacionRodamientoPort"), GetCotizacionRodamiento.class);
    }

}
