
package edu.uade.tpo.ingsist2.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "getCotizacionRodamiento", targetNamespace = "http://facade.view.ingsist2.tpo.uade.edu/")
public interface GetCotizacionRodamiento {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.uade.tpo.ingsist2.view.facade.SolicitudCotizacionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recibirSolicitudCotizacion", targetNamespace = "http://facade.view.ingsist2.tpo.uade.edu/", className = "edu.uade.tpo.ingsist2.view.facade.RecibirSolicitudCotizacion")
    @ResponseWrapper(localName = "recibirSolicitudCotizacionResponse", targetNamespace = "http://facade.view.ingsist2.tpo.uade.edu/", className = "edu.uade.tpo.ingsist2.view.facade.RecibirSolicitudCotizacionResponse")
    public SolicitudCotizacionResponse recibirSolicitudCotizacion(
        @WebParam(name = "arg0", targetNamespace = "")
        SolicitudCotizacionRequest arg0);

}
